// eslint-disable-next-line no-unused-expressions
export const Personas = [
  {
    name: "Harry Potter",
    alternate_names: [],
    species: "human",
    gender: "male",
    house: "Gryffindor",
    dateOfBirth: "31-07-1980",
    yearOfBirth: 1980,
    wizard: true,
    ancestry: "half-blood",
    eyeColour: "green",
    hairColour: "black",
    wand: {
      wood: "holly",
      core: "phoenix feather",
      length: 11,
    },
    patronus: "stag",
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: "Daniel Radcliffe",
    alternate_actors: [""],
    alive: true,
    image: "http://hp-api.herokuapp.com/images/harry.jpg",
  },
  {
    name: "Hermione Granger",
    alternate_names: [""],
    species: "human",
    gender: "female",
    house: "Gryffindor",
    dateOfBirth: "19-09-1979",
    yearOfBirth: 1979,
    wizard: true,
    ancestry: "muggleborn",
    eyeColour: "brown",
    hairColour: "brown",
    wand: {
      wood: "vine",
      core: "dragon heartstring",
      length: "",
    },
    patronus: "otter",
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: "Emma Watson",
    alternate_actors: [""],
    alive: true,
    image: "http://hp-api.herokuapp.com/images/hermione.jpeg",
  },
  {
    name: "Ron Weasley",
    alternate_names: [""],
    species: "human",
    gender: "male",
    house: "Gryffindor",
    dateOfBirth: "01-03-1980",
    yearOfBirth: 1980,
    wizard: true,
    ancestry: "pure-blood",
    eyeColour: "blue",
    hairColour: "red",
    wand: {
      wood: "willow",
      core: "unicorn tail-hair",
      length: 14,
    },
    patronus: "Jack Russell terrier",
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: "Rupert Grint",
    alternate_actors: [""],
    alive: true,
    image: "http://hp-api.herokuapp.com/images/ron.jpg",
  },
  {
    name: "Minerva McGonagall",
    alternate_names: [""],
    species: "human",
    gender: "female",
    house: "Gryffindor",
    dateOfBirth: "04-10-1925",
    yearOfBirth: 1925,
    wizard: true,
    ancestry: "",
    eyeColour: "",
    hairColour: "black",
    wand: {
      wood: "",
      core: "",
      length: "",
    },
    patronus: "tabby cat",
    hogwartsStudent: false,
    hogwartsStaff: true,
    actor: "Dame Maggie Smith",
    alternate_actors: [""],
    alive: true,
    image: "http://hp-api.herokuapp.com/images/mcgonagall.jpg",
  },
  {},
  {
    name: "Neville Longbottom",
    alternate_names: [""],
    species: "human",
    gender: "male",
    house: "Gryffindor",
    dateOfBirth: "30-07-1980",
    yearOfBirth: 1980,
    wizard: true,
    ancestry: "pure-blood",
    eyeColour: "",
    hairColour: "blonde",
    wand: {
      wood: "cherry",
      core: "unicorn tail-hair",
      length: 13,
    },
    patronus: "",
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: "Matthew Lewis",
    alternate_actors: [""],
    alive: true,
    image: "http://hp-api.herokuapp.com/images/neville.jpg",
  },
  {
    name: "Ginny Weasley",
    alternate_names: [""],
    species: "human",
    gender: "female",
    house: "Gryffindor",
    dateOfBirth: "11-08-1981",
    yearOfBirth: 1981,
    wizard: true,
    ancestry: "pure-blood",
    eyeColour: "brown",
    hairColour: "red",
    wand: {
      wood: "yew",
      core: "",
      length: "",
    },
    patronus: "horse",
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: "Bonnie Wright",
    alternate_actors: [""],
    alive: true,
    image: "http://hp-api.herokuapp.com/images/ginny.jpg",
  },
  {
    name: "Sirius Black",
    alternate_names: ["Padfoot", "Snuffles"],
    species: "human",
    gender: "male",
    house: "Gryffindor",
    dateOfBirth: "03-11-1959",
    yearOfBirth: 1959,
    wizard: true,
    ancestry: "pure-blood",
    eyeColour: "grey",
    hairColour: "black",
    wand: {
      wood: "",
      core: "",
      length: "",
    },
    patronus: "hare",
    hogwartsStudent: false,
    hogwartsStaff: false,
    actor: "Gary Oldman",
    alternate_actors: ["James Walters", "Rohan Gotobed"],
    alive: false,
    image: "http://hp-api.herokuapp.com/images/sirius.JPG",
  },
  {
    name: "Remus Lupin",
    alternate_names: ["Professor Lupin", "Moony"],
    species: "werewolf",
    gender: "male",
    house: "Gryffindor",
    dateOfBirth: "10-03-1960",
    yearOfBirth: 1960,
    wizard: true,
    ancestry: "half-blood",
    eyeColour: "green",
    hairColour: "brown",
    wand: {
      wood: "cypress",
      core: "unicorn tail-hair",
      length: 10.25,
    },
    patronus: "wolf",
    hogwartsStudent: false,
    hogwartsStaff: true,
    actor: "David Thewlis",
    alternate_actors: [""],
    alive: false,
    image: "http://hp-api.herokuapp.com/images/lupin.jpg",
  },
  {
    name: "Arthur Weasley",
    alternate_names: [""],
    species: "human",
    gender: "male",
    house: "Gryffindor",
    dateOfBirth: "06-02-1950",
    yearOfBirth: 1950,
    wizard: true,
    ancestry: "pure-blood",
    eyeColour: "blue",
    hairColour: "red",
    wand: {
      wood: "",
      core: "",
      length: "",
    },
    patronus: "weasel",
    hogwartsStudent: false,
    hogwartsStaff: false,
    actor: "Mark Williams",
    alternate_actors: [""],
    alive: true,
    image: "http://hp-api.herokuapp.com/images/arthur.jpg",
  },
];
